"""create core tables

Revision ID: 51064ed56cbe
Revises: 
Create Date: 2026-10-04 05:19:21.344721

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision: str = '51064ed56cbe'
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('suite_name', sa.String(length=255), nullable=True),
    sa.Column('classname', sa.String(length=1024), nullable=False),
    sa.Column('test_name', sa.String(length=1024), nullable=False),
    sa.Column('unique_key', sa.String(length=2048), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_cases_last_seen', 'test_cases', ['last_seen_at'], unique=False)
    op.create_index('ix_test_cases_project_class_name', 'test_cases', ['project_id', 'classname', 'test_name'], unique=False)
    op.create_index(op.f('ix_test_cases_unique_key'), 'test_cases', ['unique_key'], unique=True)
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('error_tests', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'run_number', name='uq_test_runs_project_run')
    )
    op.create_index(op.f('ix_test_runs_created_at'), 'test_runs', ['created_at'], unique=False)
    op.create_index('ix_test_runs_project_branch', 'test_runs', ['project_id', 'branch'], unique=False)
    op.create_index('ix_test_runs_project_created', 'test_runs', ['project_id', 'created_at'], unique=False)
    op.create_table('test_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('failure_type', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('passed', 'failed', 'error', 'skipped')", name='ck_test_executions_status'),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_executions_case_time', 'test_executions', ['test_case_id', 'executed_at'], unique=False)
    op.create_index('ix_test_executions_executed_at', 'test_executions', ['executed_at'], unique=False)
    op.create_index('ix_test_executions_run_id', 'test_executions', ['run_id'], unique=False)
    op.create_index('ix_test_executions_test_case_id', 'test_executions', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_executions_test_case_id', table_name='test_executions')
    op.drop_index('ix_test_executions_run_id', table_name='test_executions')
    op.drop_index('ix_test_executions_executed_at', table_name='test_executions')
    op.drop_index('ix_test_executions_case_time', table_name='test_executions')
    op.drop_table('test_executions')
    op.drop_index('ix_test_runs_project_created', table_name='test_runs')
    op.drop_index('ix_test_runs_project_branch', table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_created_at'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_cases_unique_key'), table_name='test_cases')
    op.drop_index('ix_test_cases_project_class_name', table_name='test_cases')
    op.drop_index('ix_test_cases_last_seen', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_table('projects')
    # ### end Alembic commands ###
