import type {
  DashboardSummary,
  HistoryPoint,
  Project,
  TestDetail,
  TestListItem,
  TestRun,
} from './api/types';

export const sampleSummary: DashboardSummary = {
  total_tests: 35,
  total_runs: 51,
  stable_tests: 17,
  suspected_flaky_tests: 5,
  highly_flaky_tests: 2,
  consistently_failing_tests: 3,
  slow_tests: 2,
  newly_flaky_tests: 2,
  average_pass_rate: 0.767,
};

export const sampleProjects: Project[] = [
  {
    id: 1,
    name: 'demo-project',
    repository: null,
    created_at: '2026-01-01T00:00:00Z',
    run_count: 51,
    test_count: 35,
  },
];

export const sampleRuns: TestRun[] = [
  {
    id: 51,
    project_id: 1,
    project_name: 'demo-project',
    run_number: 51,
    branch: 'main',
    commit_sha: null,
    workflow_name: null,
    environment: null,
    started_at: null,
    finished_at: null,
    total_tests: 5,
    passed_tests: 2,
    failed_tests: 1,
    skipped_tests: 1,
    error_tests: 1,
    total_duration: 4.2,
    source: 'junit',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 50,
    project_id: 1,
    project_name: 'demo-project',
    run_number: 50,
    branch: 'dev',
    commit_sha: null,
    workflow_name: null,
    environment: null,
    started_at: null,
    finished_at: null,
    total_tests: 30,
    passed_tests: 28,
    failed_tests: 2,
    skipped_tests: 0,
    error_tests: 0,
    total_duration: 60.0,
    source: 'junit',
    created_at: '2026-01-01T00:00:00Z',
  },
];

function baseItem(overrides: Partial<TestListItem>): TestListItem {
  return {
    test_case_id: 1,
    unique_key: 'demo-project::tests.test_auth::test_login_valid',
    project_id: 1,
    project_name: 'demo-project',
    suite_name: 'auth',
    classname: 'tests.test_auth',
    test_name: 'test_login_valid',
    classification: 'STABLE',
    flakiness_score: 0,
    pass_rate: 1,
    failure_rate: 0,
    sample_size: 50,
    pass_rate_delta: 0,
    score_delta: 0,
    avg_duration: 0.3,
    last_seen_at: '2026-01-01T00:00:00Z',
    newly_flaky: false,
    is_slow: false,
    ...overrides,
  };
}

export const sampleFlakyItems: TestListItem[] = [
  baseItem({
    test_case_id: 23,
    unique_key: 'demo-project::tests.test_auth::test_session_refresh',
    test_name: 'test_session_refresh',
    classification: 'HIGHLY_FLAKY',
    flakiness_score: 82.03,
    pass_rate: 0.5,
    failure_rate: 0.5,
  }),
  baseItem({
    test_case_id: 19,
    unique_key: 'demo-project::tests.test_payments::test_payment_timeout',
    suite_name: 'payments',
    classname: 'tests.test_payments',
    test_name: 'test_payment_timeout',
    classification: 'SUSPECTED_FLAKY',
    flakiness_score: 59.64,
    pass_rate: 0.66,
    failure_rate: 0.34,
    newly_flaky: true,
  }),
];

export const sampleDetail: TestDetail = {
  ...baseItem({
    test_case_id: 23,
    unique_key: 'demo-project::tests.test_auth::test_session_refresh',
    test_name: 'test_session_refresh',
    classification: 'HIGHLY_FLAKY',
    flakiness_score: 82.03,
    pass_rate: 0.5,
  }),
  passed: 25,
  failed: 25,
  error: 0,
  skipped: 0,
  failure_rate: 0.5,
  duration_min: 0.2,
  duration_max: 1.1,
  duration_mean: 0.55,
  duration_median: 0.5,
  duration_p95: 1.0,
  duration_stddev: 0.2,
  inconsistency: 1,
  recency: 0.51,
  duration_instability: 0.05,
  persistently_flaky: true,
  pass_rate_delta: 0,
  failure_rate_delta: 0,
  duration_delta: 0.1,
  score_delta: 0.14,
};

export const sampleHistory: HistoryPoint[] = [
  {
    run_id: 1,
    run_number: 1,
    branch: 'main',
    status: 'passed',
    duration: 0.5,
    executed_at: '2026-01-01T00:00:00Z',
    score: 0,
    failure_message: null,
    failure_type: null,
  },
  {
    run_id: 2,
    run_number: 2,
    branch: 'main',
    status: 'failed',
    duration: 0.9,
    executed_at: '2026-01-01T01:00:00Z',
    score: 35.5,
    failure_message: 'AssertionError: race on refresh',
    failure_type: 'AssertionError',
  },
  {
    run_id: 3,
    run_number: 3,
    branch: 'main',
    status: 'failed',
    duration: 0.9,
    executed_at: '2026-01-01T02:00:00Z',
    score: 35.5,
    failure_message: 'AssertionError: race on refresh',
    failure_type: 'AssertionError',
  },
];
